Initial prototype
DAT-05-02/P5 pull request #47
Opened 2023-10-10 08:58 UTC by thomaskettunen

Created model using tensorflow. It reads the images generated from run, and gets the labels(species) from the generated csv file. it then trains using most of these images, and the rest for validation. The layers in the model are the input layer, which is a Conv2D layer, which for each pixel in the image creates a tensor. Then it uses a MaxPooling2D, to reduce the image size while trying to retain the most important information, this is set to (2, 2), which means it takes the max value in 2x2 squares of pixels in the image. It then does this 2 more times, before flattening, which means it converts its input to a vector, which is necessary before it can be used as an input to the dense layer. The final layer is just a dense layer, which has tensors corresponding, to each different possible species then the layer.

closes #24

2023-10-10 09:24 UTC, khmikkelsen requested changes
line 42 unnecessary. 
csv should be rewrote to use pandas instead.

2023-10-10 09:24 UTC, khmikkelsen requested changes
line 42 unnecessary. 
csv should be rewrote to use pandas instead.

2023-10-10 09:59 UTC, lucas2000k requested changes
+1

2023-10-23 08:54 UTC, lucas2000k approved these changes

2023-10-23 08:54 UTC, MartinCornelius approved these changes

2023-10-23 09:17 UTC, khmikkelsen approved these changes

2023-10-23 09:17 UTC, merged